"""Write src/04-logic-pack.js: the logic pack's semantics for the editor, from packs/logic/gates.json.

The editor is one self-contained page, so the pack travels inside it as a script. Only what
the runtime reads is carried (kinds, pins, tables, params, delays); glyphs reach the editor
through each gate's `presentation.graphic`. `--check` exits 1 when the file differs from what
this would write.

    python scripts/build_logic_pack_js.py
    python scripts/build_logic_pack_js.py --check
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PACK = ROOT / 'packs' / 'logic' / 'gates.json'
TARGET = ROOT / 'src' / '04-logic-pack.js'
CARRIED = ('kind', 'inputs', 'outputs', 'table', 'state', 'clock', 'edge', 'next', 'output', 'initial', 'params', 'delay')


def text() -> str:
    pack = json.loads(PACK.read_text(encoding='utf-8'))
    slim = {k: v for k, v in pack.items() if k != 'gates'}
    slim['gates'] = {name: {k: g[k] for k in CARRIED if k in g} for name, g in pack['gates'].items()}
    body = json.dumps(slim, sort_keys=True, separators=(',', ':'), ensure_ascii=False)
    return ("'use strict';\n// Generated by scripts/build_logic_pack_js.py from packs/logic/gates.json; do not edit.\n"
            f"(typeof globalThis!=='undefined'?globalThis:this).SovSchematicLogicPack={body};\n")


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split('\n')[0])
    ap.add_argument('--check', action='store_true')
    args = ap.parse_args(argv)
    want = text()
    if args.check:
        if not TARGET.exists() or TARGET.read_text(encoding='utf-8') != want:
            print(f'stale {TARGET.relative_to(ROOT)}')
            return 1
        return 0
    TARGET.write_text(want, encoding='utf-8', newline='\n')
    print(f'wrote {TARGET.relative_to(ROOT)}')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
