"""Measure colour on the rendered canvas and write contrast-audit.md.

Two measurements, both taken from the running editor (src/09-colour-core.js, src/59-contrast.js):

1. Palettes, as realised on screen for every appearance x theme x palette: each colour slot
   against the canvas (the theme's floor, never below WCAG 2.2 SC 1.4.11's 3:1), and, for the
   categorical rows, the closest pair of slots under normal, protan, deutan and tritan vision
   (Machado 2009 simulation, OKLab distance). A hue-family palette that is not colour-blind
   distinct is reported, not failed; the default palette must be distinct.
2. Documents: every label (SC 1.4.3: 4.5:1, large text 3:1) and every mark a reader needs
   (SC 1.4.11: 3:1) in each example, light and dark, against what is painted beneath it.

Usage:
    python scripts/contrast_audit.py                 # measure, print, exit 1 on a failure
    python scripts/contrast_audit.py --write         # also rewrite contrast-audit.md
    python scripts/contrast_audit.py a.sov --json out.json
"""
from __future__ import annotations
import argparse, json, sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / 'tests'))
from browser_runtime import chromium_launch_kwargs  # noqa: E402

THEMES = ['pastel', 'subtle', 'reading']
APPEARANCES = ['light', 'dark']
DEFAULT_PALETTE = 'okabe-ito'


def measure(paths: list[Path]) -> dict:
    from playwright.sync_api import sync_playwright
    html = (ROOT / 'index.html').read_text(encoding='utf-8')
    out = {'palettes': [], 'documents': [], 'sources': [], 'floors': {}}
    with sync_playwright() as p:
        browser = p.chromium.launch(**chromium_launch_kwargs(disable_gpu=True))
        page = browser.new_page(viewport={'width': 1600, 'height': 1000})
        errors: list[str] = []
        page.on('pageerror', lambda exc: errors.append(str(exc)))
        page.set_content(html, wait_until='load')
        page.wait_for_timeout(250)
        out['sources'] = page.evaluate('()=>SovSchematicColour.SOURCES')
        out['floors'] = page.evaluate('()=>({...SovSchematicColour.WCAG,cvd:SovSchematicColour.CVD_FLOOR})')
        palettes = [p for p in page.evaluate('()=>SovSchematicAPI.view.colour().palettes') if p != 'custom']
        for appearance in APPEARANCES:
            page.evaluate('(m)=>SovSchematicAPI.view.setAppearance(m)', appearance)
            for theme in THEMES:
                for palette in palettes:
                    page.evaluate('(c)=>SovSchematicAPI.view.setColour(c)', {'theme': theme, 'palette': palette})
                    out['palettes'].append(page.evaluate('()=>SovSchematicAPI.view.paletteAudit()'))
            page.evaluate('(c)=>SovSchematicAPI.view.setColour(c)', {'theme': 'pastel', 'palette': DEFAULT_PALETTE})
            for src in paths:
                page.evaluate('([t,n])=>SovSchematicAPI.file.open(t,n)', [src.read_text(encoding='utf-8'), src.name])
                page.evaluate('()=>{ if (typeof fitDiagram === "function") fitDiagram(); }')
                page.wait_for_timeout(200)
                r = page.evaluate('()=>SovSchematicAPI.layout.contrast({static:true})')
                r['source'] = src.name
                r['appearance'] = appearance
                out['documents'].append(r)
        browser.close()
        if errors:
            raise SystemExit('page errors: ' + '; '.join(errors))
    return out


def failures(result: dict) -> list[str]:
    bad = []
    for r in result['palettes']:
        for f in r['failures']:
            if f['kind'] == 'contrast' or r['palette'] == DEFAULT_PALETTE:
                bad.append(f"palette {r['appearance']}/{r['theme']}/{r['palette']}: {f}")
    for d in result['documents']:
        for f in d['findings']:
            bad.append(f"{d['source']} ({d['appearance']}): {f['kind']} {f['ids']} {f['detail']}")
    return bad


def report(result: dict) -> str:
    fl = result['floors']
    lines = [
        '# Contrast audit',
        '',
        'Generated by `python scripts/contrast_audit.py --write` from the running editor. Every number is measured',
        'on the rendered canvas or on the palette as realised on screen, never on the authored hex values.',
        '',
        f"Floors: text {fl['text']}:1, large text {fl['largeText']}:1 (WCAG 2.2 SC 1.4.3); marks and palette slots",
        f"{fl['nonText']}:1 (SC 1.4.11), raised per theme (pastel 3.25, subtle 3.5, reading 4.0). Colour-blind",
        f"distinctness: the closest pair of colour slots at least {fl['cvd']} apart in OKLab under normal, protan,",
        'deutan and tritan simulation (about two and a half just-noticeable differences).',
        '',
        '## Palettes',
        '',
        '| Appearance | Theme | Palette | Min contrast | Floor | Closest pair (normal / protan / deutan / tritan) | Colour-blind distinct | Result |',
        '|---|---|---|---:|---:|---|---|---|',
    ]
    for r in result['palettes']:
        c = r['closest']
        pair = ' / '.join(f"{c[v]['distance']:.3f}" for v in ['normal', 'protan', 'deutan', 'tritan'])
        contrast_ok = not any(f['kind'] == 'contrast' for f in r['failures'])
        distinct = r['minDistance'] >= fl['cvd']
        cvd = 'n/a (mono)' if not r['categorical'] else ('yes' if distinct else 'no')
        verdict = 'PASS' if contrast_ok and (distinct or r['palette'] != DEFAULT_PALETTE) else 'FAIL'
        if verdict == 'PASS' and r['categorical'] and not distinct:
            verdict = 'PASS (hue family)'
        lines.append(f"| {r['appearance'].title()} | {r['theme'].title()} | {r['palette']} | {r['minContrast']:.2f}:1 | {r['floor']}:1 | {pair} | {cvd} | {verdict} |")
    lines += ['', '## Documents', '', '| Document | Appearance | Items measured | Text below floor | Marks below floor |', '|---|---|---:|---:|---:|']
    for d in result['documents']:
        lines.append(f"| {d['source']} | {d['appearance']} | {d['checked']} | {d['counts'].get('text-contrast', 0)} | {d['counts'].get('mark-contrast', 0)} |")
    bad = failures(result)
    lines += ['', f"**Overall: {'PASS' if not bad else 'FAIL'}**", '']
    for b in bad:
        lines.append(f'- {b}')
    lines += ['', '## Sources', ''] + [f'- {s}' for s in result['sources']] + ['']
    return '\n'.join(lines)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument('files', nargs='*')
    ap.add_argument('--write', action='store_true', help='rewrite contrast-audit.md')
    ap.add_argument('--json')
    a = ap.parse_args()
    paths = [Path(f).resolve() for f in a.files] or sorted((ROOT / 'examples').glob('*.sov'))
    result = measure(paths)
    text = report(result)
    print(text)
    if a.write:
        (ROOT / 'contrast-audit.md').write_text(text, encoding='utf-8', newline='\n')
    if a.json:
        Path(a.json).write_text(json.dumps(result, indent=2, sort_keys=True) + '\n', encoding='utf-8')
    return 1 if failures(result) else 0


if __name__ == '__main__':
    raise SystemExit(main())
